//LAMBERT PROBLEM
//deltaPhi = 2PI(Thohmann/Touter)
//phiDot = nInner - nOuter

//STEP 1: DETERMINE ORBIT OF TARGET (Lambert) given r(t1) and r(t2)
//STEP 2: DETERMINE DESIRED POSITION OF TARGET
//STEP 3: FIND INTERCEPT TRAJECTORY
//STEP 4: CALCULATE DELTAV
